"""Tests for JavaScript test editing utilities."""

from __future__ import annotations

from pathlib import Path

import pytest

from codeflash.languages.javascript.edit_tests import inject_test_globals
from codeflash.models.models import GeneratedTests, GeneratedTestsList


class TestInjectTestGlobals:
    """Tests for inject_test_globals function."""

    def test_vitest_import_already_present_different_order(self):
        """Test that vitest imports generated by LLM are not duplicated.

        The LLM generates imports like:
            import { describe, test, expect, vi, beforeEach, afterEach } from 'vitest';

        The hardcoded import in inject_test_globals is:
            import { vi, describe, it, expect, beforeEach, afterEach, beforeAll, test } from 'vitest'

        These should be detected as duplicates even though they're not identical strings.

        This is the bug: the current code does a substring match which fails.
        """
        # Simulate LLM-generated test with vitest imports already present
        llm_generated_test = """import { describe, test, expect, vi, beforeEach, afterEach } from 'vitest';
import { createConfigIO } from '../src/config/io';

describe('createConfigIO', () => {
    test('should work', () => {
        expect(true).toBe(true);
    });
});
"""

        test = GeneratedTests(
            generated_original_test_source=llm_generated_test,
            instrumented_behavior_test_source=llm_generated_test,
            instrumented_perf_test_source=llm_generated_test,
            behavior_file_path=Path("/tmp/test_behavior.test.ts"),
            perf_file_path=Path("/tmp/test_perf.test.ts"),
        )

        generated_tests = GeneratedTestsList(
            generated_tests=[test],
        )

        result = inject_test_globals(
            generated_tests=generated_tests,
            module_system="esm",
            test_framework="vitest",
        )

        # The bug: current implementation adds duplicate imports
        # After the fix, there should be NO duplicate imports

        # Count how many vitest imports are in the result
        import_count = result.generated_tests[0].generated_original_test_source.count("from 'vitest'")

        # Should be exactly 1, but with the bug it's 2
        assert import_count == 1, (
            f"Expected exactly 1 vitest import, but found {import_count}. "
            f"Test source:\n{result.generated_tests[0].generated_original_test_source}"
        )

    def test_vitest_import_not_present_should_inject(self):
        """Test that vitest imports are injected when not present."""
        test_without_imports = """import { createConfigIO } from '../src/config/io';

describe('createConfigIO', () => {
    test('should work', () => {
        expect(true).toBe(true);
    });
});
"""

        test = GeneratedTests(
            generated_original_test_source=test_without_imports,
            instrumented_behavior_test_source=test_without_imports,
            instrumented_perf_test_source=test_without_imports,
            behavior_file_path=Path("/tmp/test_behavior.test.ts"),
            perf_file_path=Path("/tmp/test_perf.test.ts"),
        )

        generated_tests = GeneratedTestsList(
            generated_tests=[test],
        )

        result = inject_test_globals(
            generated_tests=generated_tests,
            module_system="esm",
            test_framework="vitest",
        )

        # Should have exactly 1 vitest import
        import_count = result.generated_tests[0].generated_original_test_source.count("from 'vitest'")
        assert import_count == 1, f"Expected exactly 1 vitest import, found {import_count}"

        # Should start with the vitest import
        assert result.generated_tests[0].generated_original_test_source.startswith("import {")

    def test_jest_import_already_present(self):
        """Test that jest imports are not duplicated."""
        llm_generated_test = """import { describe, test, expect, beforeEach, afterEach } from '@jest/globals';
import { myFunc } from '../src/myFunc';

describe('myFunc', () => {
    test('should work', () => {
        expect(true).toBe(true);
    });
});
"""

        test = GeneratedTests(
            generated_original_test_source=llm_generated_test,
            instrumented_behavior_test_source=llm_generated_test,
            instrumented_perf_test_source=llm_generated_test,
            behavior_file_path=Path("/tmp/test_behavior.test.ts"),
            perf_file_path=Path("/tmp/test_perf.test.ts"),
        )

        generated_tests = GeneratedTestsList(
            generated_tests=[test],
        )

        result = inject_test_globals(
            generated_tests=generated_tests,
            module_system="esm",
            test_framework="jest",
        )

        # Should have exactly 1 jest import
        import_count = result.generated_tests[0].generated_original_test_source.count("from '@jest/globals'")
        assert import_count == 1, f"Expected exactly 1 jest import, found {import_count}"

    def test_mocha_with_assert_import(self):
        """Test that mocha tests with assert imports are not duplicated."""
        llm_generated_test = """import assert from 'node:assert/strict';
import { myFunc } from '../src/myFunc';

describe('myFunc', () => {
    it('should work', () => {
        assert.strictEqual(1, 1);
    });
});
"""

        test = GeneratedTests(
            generated_original_test_source=llm_generated_test,
            instrumented_behavior_test_source=llm_generated_test,
            instrumented_perf_test_source=llm_generated_test,
            behavior_file_path=Path("/tmp/test_behavior.test.ts"),
            perf_file_path=Path("/tmp/test_perf.test.ts"),
        )

        generated_tests = GeneratedTestsList(
            generated_tests=[test],
        )

        result = inject_test_globals(
            generated_tests=generated_tests,
            module_system="esm",
            test_framework="mocha",
        )

        # Should have exactly 1 assert import
        import_count = result.generated_tests[0].generated_original_test_source.count("from 'node:assert/strict'")
        assert import_count == 1, f"Expected exactly 1 assert import, found {import_count}"
