[tool.codeflash]
disable-imports-sorting = true
disable-telemetry = true
formatter-cmds = ["uv run ruff check --exit-zero --fix $file", "uv run ruff format $file"]
module-root = "src/aviary"
test-framework = "pytest"
tests-root = "tests"