repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --config=pyproject.toml ]
    # Run the formatter.
    - id: ruff-format