MAX_TEST_RUN_ITERATIONS = 5
INDIVIDUAL_TESTCASE_TIMEOUT = 15
MAX_FUNCTION_TEST_SECONDS = 60
N_CANDIDATES = 10
MIN_IMPROVEMENT_THRESHOLD = 0.05
MAX_TEST_FUNCTION_RUNS = 10000
MAX_CUMULATIVE_TEST_RUNTIME_NANOSECONDS = 10e9  # 10s
REPEAT_COUNT = 2
