name: end-to-end-test

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  topological-sort-optimization:
    environment: external-trusted-contributors
    runs-on: ubuntu-latest
    env:
      CODEFLASH_AIS_SERVER: prod
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      COLUMNS: 110
      MAX_RETRIES: 3
      RETRY_DELAY: 5
      EXPECTED_IMPROVEMENT_PCT: 5
      CODEFLASH_END_TO_END: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate PR
        run: |
          # Check for any workflow changes
          if git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | grep -q "^.github/workflows/"; then
            echo "⚠️ Workflow changes detected."
            # Get the PR author
            AUTHOR="${{ github.event.pull_request.user.login }}"
            echo "PR Author: $AUTHOR"
            # Allowlist check
            if [[ "$AUTHOR" == "misrasaurabh1" || "$AUTHOR" == "KRRT7" ]]; then
              echo "✅ Authorized user ($AUTHOR). Proceeding."
            elif [[ "${{ github.event_name }}" == "pull_request_target" && "${{ github.event.pull_request.state }}" == "open" ]]; then
              echo "✅ PR triggered by 'pull_request_target' and is open. Assuming protection rules are in place. Proceeding."
            else
              echo "⛔ Unauthorized user ($AUTHOR) attempting to modify workflows. Exiting."
              exit 1
            fi
          else
            echo "✅ No workflow file changes detected. Proceeding."
          fi

      - name: Set up Python 3.11 for CLI
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11.6

      - name: Install dependencies (CLI)
        run: |
          uv tool install poetry
          uv venv
          source .venv/bin/activate
          poetry install --with dev

      - name: Run Codeflash to optimize code
        id: optimize_code
        run: |
          source .venv/bin/activate
          poetry run python tests/scripts/end_to_end_test_topological_sort.py
