name: windows-unit-tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  windows-unit-tests:
    continue-on-error: true
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: install dependencies
        run: uv sync

      - name: Unit tests
        run: uv run pytest tests/
